### ISSUE TITLE
Research about Carts

### ISSUE THREAD

**Issue by nicobytes** [PlatziLabs/fake-api-backend#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by richruizv** [comment]
## Research the best practices for storing the information:

I made a quick research about how other carts save the cart and products, and there are different approach

### Examples of other shopping carts
- [https://api.opencart-api.com/demo/shopping-cart/](https://api.opencart-api.com/demo/shopping-cart/)
    
    This API stores all the items in the cookies of the application.
    
- [https://rapidapi.com/stefan.skliarov/api/API2Cart/details](https://rapidapi.com/stefan.skliarov/api/API2Cart/details)

     This API stores the product in the session of the application

- [https://fakestoreapi.com/](https://fakestoreapi.com/)
    
    This API stores the chart in a MongoDB using Mongoose
    
### Best practices

I found the following article, and make a resume about it.
    
[https://www.wiliam.com.au/wiliam-blog/where-should-you-store-your-cart](https://www.wiliam.com.au/wiliam-blog/where-should-you-store-your-cart)
    
Ways of storing information:
    
- **Session**. This is a quick and easy method to store unsecured information as it disposes of itself and becomes inaccessible to the user once they have closed their browser. This itself can be considered a con, which is when you might look at other options
- **Cookies**. the information will save on the client’s side, and we need to be aware that our users can manipulate the information. Also, the max size is 4kb.
- **Web storage**: it’s similar to cookies but with a 5MB of data limit. And apparently more secure
- **Database**: it’s good to save the information in a database especially if you want the information for your analysis. If your website is anonymous you can save the cookie id and link it with your data **you might want to consider your Privacy Policy in this instance**
    
### Conclussion

The objective of this shopping cart is to give the users a tool for practice, so I don't think that we need to analyze the information of the stored products. I would pick **session storage** because is very easy to create

**Comment by nicobytes** [comment]
@richruizv I agree with you. I think the way is by session with JWT and I think the workflow could be like that:

1. Login as a user to obtain a JWT Token.
2. Create a new cart `[POST]/cart` and get the cartID from it, include the JWT token in the headers to identify the user.
3. Add products to `[POST]/cart/cartID/products` with productID to order
4. Use `[GET]/cart/cartID` to list all product relationships with an cart and shoe details.
